//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int State { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
